const sdata = [{
    category:"Webseries",
    sname:"Stranger things",
    imgsrc:"https://i.scdn.co/image/ab67616d0000b273bd0db295c0164ddbc0584ebb",
    discription:"#1 trending content",
    links:"https://www.netflix.com/in/title/80057281",
},
{
    category:"Webseries",
    sname:"The Vampire Daries",
    imgsrc:"https://flxt.tmsimg.com/assets/p10700229_b1t_v9_aa.jpg",
    discription:"#2 trending content",
    links:"https://www.netflix.com/in/title/70143860",
},
{
    category:"Webseries",
    sname:"Dark",
    imgsrc:"https://w0.peakpx.com/wallpaper/602/919/HD-wallpaper-dark-netflix-serie-dark-netflix-serie-thumbnail.jpg",
    discription:"#3 trending content",
    links:"https://www.netflix.com/in/title/80100172",
},
{
    category:"Webseries",
    sname:"Game Of Thrones",
    imgsrc:"https://i.pinimg.com/736x/ca/30/fe/ca30fe76d4a644b358ae8394ab569408.jpg",
    discription:"#4 trending content",
    links:"https://www.hbo.com/game-of-thrones",
},
{
    category:"Webseries",
    sname:"Moon Night",
    imgsrc:"https://m.media-amazon.com/images/M/MV5BYTc5OWNhYjktMThlOS00ODUxLTgwNDQtZjdjYjkyM2IwZTZlXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_FMjpg_UX1000_.jpg",
    discription:"#5 trending content",
    links:"https://www.imdb.com/title/tt10234724/",
},
{
    category:"Webseries",
    sname:"Lucifer",
    imgsrc:"https://m.media-amazon.com/images/M/MV5BNDJjMzc4NGYtZmFmNS00YWY3LThjMzQtYzJlNGFkZGRiOWI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    discription:"#6 trending content",
    links:"https://www.netflix.com/in/title/80057918",
},
{   
    category:"Webseries",
    sname:"Peaky Blinders",
    imgsrc:"https://preview.redd.it/yib6wicssq491.jpg?auto=webp&s=9fe097a66698b8d68cec939a6b67fe0994769bfa",
    discription:"#7 trending content",
    links:"https://www.netflix.com/in/title/80002479",
},
{
    category:"Webseries",
    sname:"Money Heist",
    imgsrc:"https://m.media-amazon.com/images/M/MV5BMGUyOTFkMzUtOTQ5ZC00YjMzLWIyMGMtOWU2M2VkMDMxZTRjXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_.jpg",
    discription:"#8 trending content",
    links:"https://www.netflix.com/in/title/80192098",
},
{
    category:"Webseries",
    sname:"The Witcher",
    imgsrc:"https://m.media-amazon.com/images/M/MV5BN2FiOWU4YzYtMzZiOS00MzcyLTlkOGEtOTgwZmEwMzAxMzA3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    discription:"#9 trending content",
    links:"https://www.netflix.com/in/title/80189685",
},
{
    category:"Webseries",
    sname:"1899",
    imgsrc:"https://www.newstalkpro.in/wp-content/uploads/2022/11/tumblr_4bf89ad114aa156ed758a3fa77d827e9_f21db557_540.jpg",
    discription:"#10 trending content",
    links:"https://www.netflix.com/in/title/80214497",
},
{
    category:"Webseries",
    sname:"The Lord Of The Rings",
    imgsrc:"https://assets.nflxext.com/us/boxshots/hd1080/60004480.jpg",
    discription:"#11 trending content",
    links:"https://www.netflix.com/tr-en/title/60004480",
},
{
    category:"Webseries",
    sname:"House Of The Dragons",
    imgsrc:"https://img.etimg.com/thumb/msid-93706520,width-650,imgsize-165874,,resizemode-4,quality-100/house-of-the-dragon-now-released-in-india.jpg",
    discription:"#12 trending content",
    links:"https://www.hbo.com/house-of-the-dragon",
},
{
    category:"Sci-fi",
    sname:"Inseption",
    imgsrc:"https://flxt.tmsimg.com/assets/p7825626_p_v8_af.jpg",
    discription:"#1 trending content",
    links:"#",
},
{
    category:"Sci-fi",
    sname:"Lucy",
    imgsrc:"https://i.pinimg.com/originals/7b/b4/83/7bb483ad68e9bea47461f87254605bb0.jpg",
    discription:"#2 trending content",
    links:"#",
},
{
    category:"Adventure",
    sname:"The Dark Night",
    imgsrc:"https://images.moviesanywhere.com/bd47f9b7d090170d79b3085804075d41/c6140695-a35f-46e2-adb7-45ed829fc0c0.jpg",
    discription:"#1 trending content",
    links:"#",
},
{
    category:"Adventure",
    sname:"Gladiator",
    imgsrc:"https://cps-static.rovicorp.com/2/Open/Paramount_Pictures/Program/2801527/_derived_jpg_q90_310x470_m0/Gladiator_New_PA_2x3_27_1582787160051_2.jpg",
    discription:"#2 trending content",
    links:"#",
},
{
    category:"Adventure",
    sname:"Uncharted",
    imgsrc:"https://wallpapercave.com/wp/wp10471175.jpg",
    discription:"#3 trending content",
    links:"#",
},
{
    category:"Adventure",
    sname:"Synchronic",
    imgsrc:"https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/Synchronic_poster.jpeg/220px-Synchronic_poster.jpeg",
    discription:"#4 trending content",
    links:"#",
},
{
    category:"Adventure",
    sname:"Lara Croft Tomb Rider",
    imgsrc:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3Hm5wwNCp3oPUggEQ6Yr-wQ4ayKBZUjJJMCS3HtlZKxs6unaxsFK_RjOvDRs1FbiWwTM&usqp=CAU",
    discription:"#5 trending content",
    links:"#",
},
{
    category:"Adventure",
    sname:"Mad Max Fury Road",
    imgsrc:"https://flxt.tmsimg.com/assets/p10854488_p_v8_ao.jpg",
    discription:"#6 trending content",
    links:"#",
},
{
    category:"Adventure",
    sname:"The Gray Man",
    imgsrc:"https://dnm.nflximg.net/api/v6/2DuQlx0fM4wd1nzqm5BFBi6ILa8/AAAAQSyLZLZwAO4dhNSy1a4Ar1v5XVW6PFNlVTm1PsvQ5wOGWw5FyP6KBtS_kBpammLt5HC_TTRQrEPNT1So3yI6ORY_hbZfE4BzCP22OKvCxuiX8AI4noGLT-vnr4AQ47x44Tt6infKldGK-MhcuMsmzRmG.jpg?r=d76",
    discription:"#7 trending content",
    links:"#",
},
{
    category:"Horror",
    sname:"1922",
    imgsrc:"https://www.themoviedb.org/t/p/original/7fHnDsYvXpmZvhmWAm8RtyITaKN.jpg",
    title:"Netflix Orginal Series",
    links:"#",
},
{
    category:"Horror",
    sname:"Cam",
    imgsrc:"https://upload.wikimedia.org/wikipedia/en/c/c6/CamPoster.jpg",
    title:"Netflix Orginal Series",
    links:"#",
},
{
    category:"Horror",
    sname:"Ouija",
    imgsrc:"https://m.media-amazon.com/images/M/MV5BMTk4NTcxNTQ5NF5BMl5BanBnXkFtZTgwNTk5OTU4OTE@._V1_QL75_UX190_CR0,0,190,281_.jpg",
    title:"Netflix Orginal Series",
    links:"#",
},
{
    category:"Horror",
    sname:"The Circle",
    imgsrc:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-71GjvMkB5dLVLVY2W7_8tYgBpi1bCQXSlhg0hE4OVuyvkgsTuWoaygYy_MDcivfo2rY&usqp=CAU",
    title:"Netflix Orginal Series",
    links:"#",
},
{
    category:"Horror",
    sname:"Evil Dead",
    imgsrc:"https://images.moviesanywhere.com/4dd817bee8a3c02ae022666a9bf10083/a7faed1b-954a-4efb-9268-ddcf80eaffdd.jpg",
    title:"Netflix Orginal Series",
    links:"#",
},
{
    category:"Horror",
    sname:"Wake Up",
    imgsrc:"https://www.gbhbl.com/wp-content/uploads/2019/11/Wake-Up-Pic-4-350x445.jpg",
    title:"Netflix Orginal Series",
    links:"#",
},
{
    category:"Sci-fi",
    sname:"Annihilation",
    imgsrc:"https://i.ytimg.com/vi/MdxYJYM33BU/movieposter_en.jpg",
    discription:"#3 trending content",
    links:"#",
},
{
    category:"Sci-fi",
    sname:"Venom",
    imgsrc:"https://images.moviesanywhere.com/631ce712afb20d255c8ceaa0eee01a3f/91673de8-1a03-44d8-bb31-3334d170f171.jpg",
    discription:"#4 trending content",
    links:"#",
},
{
    category:"Sci-fi",
    sname:"Edge of Tomorrow",
    imgsrc:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/mv5bmtc5otk4mtm3m15bml5banbnxkftztgwodcxnjg3mdeat-v1-1-1589308231.jpg?crop=1xw:1xh;center,top&resize=480:*",
    discription:"#5 trending content",
    links:"#",
},
{
    category:"Sci-fi",
    sname:"Avatar",
    imgsrc:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5JDN9Ubd2C61MUTOzfnkMso8kg21zCfTsHHJUeJP25H_Up6zjfASzq56uGkm2LnKcccA&usqp=CAU",
    discription:"#6 trending content",
    links:"#",
},
{
    category:"Sci-fi",
    sname:"Dune",
    imgsrc:"https://npr.brightspotcdn.com/dims4/default/f4912e0/2147483647/strip/true/crop/2000x3000+0+0/resize/880x1320!/quality/90/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Flegacy%2Fsites%2Fkunr%2Ffiles%2F202110%2Fdune_2021.jpg",
    discription:"#7 trending content",
    links:"#",
},
{
    category:"Comedy",
    sname:"Dont look Up",
    imgsrc:"https://m.media-amazon.com/images/M/MV5BNjZjNDE1NTYtYTgwZS00M2VmLWEyODktM2FlNjhiYTk3OGU2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg",
    discription:"#1 trending content",
    links:"#",
},
{
    category:"Comedy",
    sname:"The 40 years old vergin",
    imgsrc:"https://filmfare.wwmindia.com/content/2021/aug/best-comedy-movies-hollywood-the-40-year-old-virgin-21627884834.jpg",
    discription:"#2 trending content",
    links:"#",
},
{
    category:"Comedy",
    sname:"The Dictator",
    imgsrc:"https://filmfare.wwmindia.com/content/2021/aug/best-comedy-movies-hollywood-the-dictator.jpg",
    discription:"#3 trending content",
    links:"#",
},
{
    category:"Comedy",
    sname:"Isn't it Romantic",
    imgsrc:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/best-romantic-comedies-romantic-1585066097.jpg",
    discription:"#4 trending content",
    links:"#",
},
{
    category:"Fantacy",
    sname:"Cave",
    imgsrc:"https://wallpapercave.com/wp/wp4926089.jpg",
    discription:"#1 trending content",
    links:"#",
},
{
    category:"Fantacy",
    sname:"Into The Woods",
    imgsrc:"https://www.boredpanda.com/blog/wp-content/uploads/2022/05/fantasy-movies_65-627bb1a4081bc__700.jpg",
    discription:"#2 trending content",
    links:"#",
},
{
    category:"Fantacy",
    sname:"The Last Warrior",
    imgsrc:"https://cdn.moviefone.com/image-assets/589754/eixUfuwOxwFxsyGBavdAo1AnTPh.jpg?d=360x540&q=80",
    discription:"#3 trending content",
    links:"#",
},
{
    category:"Fantacy",
    sname:"Night Books",
    imgsrc:"https://www.naijaprey.com/wp-content/uploads/2021/09/Nightbooks.jpg",
    discription:"#4 trending content",
    links:"#",
},
{
    category:"Fantacy",
    sname:"Fantacy Island",
    imgsrc:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3OhEQyGiN2WeLpPC6Yv2Sd9cWrA9GkWlO2Q&usqp=CAU",
    discription:"#5 trending content",
    links:"#",
},
{
    category:"Fantacy",
    sname:"Aladdin",
    imgsrc:"https://www.ondvdreleases.com/uploads/posts/tt6139732.jpg",
    discription:"#6 trending content",
    links:"#",
},
{
    category:"Drama",
    sname:"Les Miserable",
    imgsrc:"https://i.pinimg.com/236x/69/db/cd/69dbcdfb39765a30e3ea0c53e8513b79--les-miserables--musical.jpg",
    discription:"#1 trending content",
    links:"#",
},
{
    category:"Drama",
    sname:"Titanic",
    imgsrc:"https://i2-prod.liverpoolecho.co.uk/incoming/article12568022.ece/ALTERNATES/s1200c/Titanic.jpg",
    discription:"#2 trending content",
    links:"#",
},
{
    category:"Drama",
    sname:"While you were sleeping",
    imgsrc:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/while-you-were-sleeping-movie-1544810376.jpg",
    discription:"#3 trending content",
    links:"#",
},
{
    category:"Drama",
    sname:"Wind River",
    imgsrc:"https://upload.wikimedia.org/wikipedia/en/2/2e/Wind_River_%282017_film%29.png",
    discription:"#4 trending content",
    links:"#",
},
{
    category:"Drama",
    sname:"The Gurdians",
    imgsrc:"https://i.pinimg.com/originals/cf/e4/ff/cfe4ff9c10816f02afb065a531c78c4e.jpg",
    discription:"#5 trending content",
    links:"#",
},
{
    category:"Drama",
    sname:"American Traitor",
    imgsrc:"https://nkiri.com/wp-content/uploads/2021/05/american-traitor-hollywood-movie.jpg",
    discription:"#6 trending content",
    links:"#",
}]

export default sdata;